### Raiz da aplicação
GET http://localhost:5229/

### Listagem de Produtos
GET http://localhost:5229/produto/listar

### Busca de Produtos por nome
GET http://localhost:5229/produto/buscar/Televisão

### Cadastro de Produtos
POST http://localhost:5229/produto/cadastrar
Content-Type: application/json

{
    "nome" : "aaaa",
    "descricao" : "Alimento",
    "valor" : 15
}


### Remoção de Produtos
DELETE http://localhost:5002/produto/deletar/9cd11376-9773-4ad4-a475-3de21e85db7c


### Alterar produto
POST http://localhost:5229/produto/alterar/354a28a5-1f48-4bc4-88f9-8793afcd5eaa
Content-Type: application/json  

{
    "nome" : "Cafe",
    "descricao" : "Vicio",
    "valor" : 15
}// sempre deixar um espaco entre o content-type e o json....