### Raiz da aplicação
GET http://localhost:5229/

### Listagem de Produtos
GET http://localhost:5229/produto/listar

### Busca de Produtos por nome
GET http://localhost:5229/produto/buscar/Televisão

### Cadastro de Produtos
PUT http://localhost:5229/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Arroz",
    "descricao" : "Alimento",
    "valor" : 15
}


### Remoção de Produtos
DELETE http://localhost:5124/produto/deletar/d7a8bb32-1b2c-4966-accf-94388808ead0


### Alterar produto
POST http://localhost:5124/produto/alterar/864c4b4d-366e-4a6b-b01e-26350486482e
Content-Type: application/json

{
    "nome" : "Arroz Alterado",
    "descricao" : "Alimento",
    "valor" : 15
}